

const COMBAT_STATUS_DEFS=Object.freeze({
  stun:Object.freeze({
    label:'기절',
    kind:'cc'
  }),
  revive:Object.freeze({
    label:'부활',
    kind:'cc'
  }),
  neutralize:Object.freeze({
    label:'무력화',
    kind:'cc'
  }),
  freeze:Object.freeze({
    label:'빙결',
    kind:'cc',
    defaults:Object.freeze({
      interval:STATUS_EFFECT_RULES.freeze.interval,
      ratio:STATUS_EFFECT_RULES.freeze.maxHealthDamageRatio,
      tickAtEnd:true
    })
  }),
  bind:Object.freeze({
    label:'속박',
    kind:'cc'
  }),
  slow:Object.freeze({
    label:'감속',
    kind:'cc',
    defaults:Object.freeze({
      factor:STATUS_EFFECT_RULES.slow.factor
    })
  }),
  zap:Object.freeze({
    label:'감전',
    kind:'cc',
    defaults:Object.freeze({
      staminaRegenMultiplier:STATUS_EFFECT_RULES.zap.staminaRegenMultiplier
    })
  }),
  discharge:Object.freeze({
    label:'방전',
    kind:'cc'
  }),
  burn:Object.freeze({
    label:'화염',
    kind:'dot',
    defaults:Object.freeze({
      interval:STATUS_EFFECT_RULES.burn.interval,
      flat:STATUS_EFFECT_RULES.burn.flatDamage,
      tickAtEnd:true,
      stackMode:'refresh-type'
    })
  }),
  poison:Object.freeze({
    label:'독',
    kind:'dot',
    defaults:Object.freeze({
      interval:CHARACTER_RULES.statusDefaults.poison.interval,
      mode:'percent',
      value:CHARACTER_RULES.statusDefaults.poison.value,
      tickAtEnd:true,
      stackMode:'refresh-type'
    })
  }),
  bleed:Object.freeze({
    label:'출혈',
    kind:'dot',
    defaults:Object.freeze({
      interval:STATUS_EFFECT_RULES.bleed.interval,
      ratio:STATUS_EFFECT_RULES.bleed.maxHealthDamageRatio,
      tickAtEnd:true,
      stackMode:'refresh-type'
    })
  }),
  sleep:Object.freeze({
    label:'수면',
    kind:'cc'
  }),
  silence:Object.freeze({
    label:'침묵',
    kind:'cc'
  })
});