

const ROOM_GAMEPLAY_PACKET_TYPES=new Set([
  'duel-windup-commit',
  'duel-windup-interrupt',
  'duel-state',
  'duel-action',
  'duel-just-dodge-confirmed',
  'duel-hit-confirmed',
  'duel-effect-event',
  'duel-field-clear',
  'duel-field-resolved',
  'duel-projectile-impact-confirmed',
  'duel-projectile-guard-resolved',
  'duel-attack-guard-resolved',
  'duel-counter-resolve',
  'duel-attack-snapshot',
  'duel-triggered-attack',
  'duel-debug-map-change',
  'duel-debug-control',
  'duel-status-apply',
  'duel-scheduled-projectile-shot',
  'duel-record-update',
  'duel-presentation',
  'duel-augment-inventory',
  'duel-feature-state',
]);