/* 헤브 공통 발사/출혈/조건 회복/피격 확정 패킷 회귀. 브라우저/WebRTC 대체 아님. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');let clock=1000,passed=0,shots=[],areas=[],fields=[],burns=[];
const c=vm.createContext({console,Map,Set,WeakMap,WeakSet,Math,performance:{now:()=>clock},EMPTY_RUNTIME_ITEMS:[],EMPTY_AUGMENT_EFFECTS:[]});
function load(p,n){vm.runInContext(fs.readFileSync(path.join(root,p),'utf8')+`;globalThis.${n}=${n};`,c)}
function test(n,fn){shots=[];areas=[];fields=[];burns=[];clock=1000;fn();passed++;console.log('PASS '+n)}
for(const n of ['characterValue','characterCount','characterSum','characterProduct','freezeCharacterData','CHARACTER_RULES'])load('src/data/'+n+'.js',n);
c.CHARACTER_DATA={};for(const item of JSON.parse(fs.readFileSync(path.join(root,'src/data/characters/index.json'))).characters){const raw=vm.runInContext('('+fs.readFileSync(path.join(root,item.path),'utf8')+')',c);c.CHARACTER_DATA[raw.id]=raw}
load('src/data/CharacterDataService.js','CharacterDataService');const ch=c.CharacterDataService.compile('hab');
c.GAME_DATA={frameMs:1000/60};c.Training={sessionMode:'training'};c.OnlineDuelService={active:false};
c.AbilityService={attackById:(character,id)=>Object.values(character.attacks).find(a=>a.id===id),damageRatio:(character,a)=>a?.damageRatio||0};
c.EntitySimulationAuthorityService={isLocal:e=>e.local!==false};c.EntityService={items:new Map(),owner:e=>e};
c.RelationService={relation:(s,t)=>s===t?'self':s.teamId===t.teamId?'ally':'enemy',canTarget:(s,t)=>s.teamId!==t.teamId};
c.AugmentService={update(){},captureResourceConditionSnapshot:()=>null,prepareAttack:(s,a)=>a,attackCostMultiplier:()=>1};c.ProgressScaledAttackService={resolve:(s,a)=>a};
c.TagService={derivedModuleTags:()=>[],attackTags:a=>new Set(a.tags||[])};c.AttackPreviewService={fromAttack:(s,a,angle,until)=>({attack:a,angle,until})};
c.StaminaService={nominalBudget:e=>e.stamina,spend:(e,n)=>{if(e.stamina<n)return false;e.stamina-=n;return true}};
c.AttackResourceConditionService={capture:()=>null};c.COMBAT_BUFF_DEFS={evasionInvulnerable:{}};c.COMBAT_STATUS_DEFS={burn:{},bleed:{},evasionInvulnerable:{}};
c.BuffService={set:()=>true,remove:()=>true};c.CCService={removeSource(){},isDotImpact:()=>false};
c.EffectSpawnService={removeKey(){},ease:v=>v,definitionSnapshot:x=>JSON.parse(JSON.stringify(x))};
c.MovementService={travelDistance:(x,y,a,d)=>d,resolveEmbedded(){},finalizeForcedMotion(){},knockback:()=>true};
c.OnlinePresentationSyncService={send(){}};c.WorldGeometryService={wallAtPoint:()=>null,nearestWallTarget:()=>null};
c.ProjectileStateService={get:()=>null};c.ProjectileService={spawn:data=>{shots.push(data);c.AttackModuleService.onDelivery(data.source,data.attack,data.angle,data.volley?.execution);return data}};
c.AreaAttackService={execute:(s,a,angle,m,v,options)=>{areas.push({s,a,angle,m,v,options});return true}};
c.InstalledAreaFieldService={KIND:'installed-area-field',containmentTravelDistance:(e,a,d)=>d,baseKey:m=>m.stateKey,activatePoint:(s,m,p,o)=>{const v={s,m,p,o};fields.push(v);return v}};
for(const [p,n]of [['src/core/GameEvents.js','GameEvents'],['src/core/TriggerConditionService.js','TriggerConditionService'],['src/core/TriggerModuleService.js','TriggerModuleService'],['src/core/ArcTrajectoryService.js','ArcTrajectoryService'],['src/core/CollisionPolicyService.js','CollisionPolicyService'],['src/combat/AttackExecutionService.js','AttackExecutionService'],['src/combat/AttackModuleService.js','AttackModuleService'],['src/projectiles/ProjectileModuleService.js','ProjectileModuleService'],['src/projectiles/ProjectileImpactService.js','ProjectileImpactService'],['src/projectiles/TargetPointProjectileService.js','TargetPointProjectileService'],['src/combat/TriggeredAttackService.js','TriggeredAttackService'],['src/combat/CounterModuleService.js','CounterModuleService'],['src/abilities/MovementAbilityService.js','MovementAbilityService'],['src/abilities/ChargedAttackService.js','ChargedAttackService'],['src/ui/CharacterDescriptionService.js','CharacterDescriptionService']])load(p,n);
load('src/core/ModeStateService.js','ModeStateService');
c.CombatStatusApplicationService={apply:ctx=>{burns.push(ctx);return true}};
function entity(extra={}){return{id:'hab',teamId:'A',kind:'player',character:ch,baseDamage:ch.baseDamage,alive:true,local:true,x:400,y:500,radius:20,stamina:1000,maxStamina:1000,actionState:new Map(),cooldowns:new Map(),statuses:new Map(),buffs:new Map(),...extra}}
const originalMovement=c.MovementAbilityService;
c.MovementAbilityService={...originalMovement,applyBuffs(){},clearBuffs(){},spawnEffects:()=>[],broadcastEffects(){}};
c.AttackService={canUse:(e,a)=>e.stamina>=a.cost,execute:(s,a,angle)=>c.TriggeredAttackService.execute(s,a,angle)};

let effects=[];c.EffectSpawnService.shouldPresentAttack=()=>true;c.EffectSpawnService.spawn=(spec,context)=>{effects.push({spec,context});return spec};c.EffectSpawnService.presentationSnapshot=x=>x;load('src/core/ColorService.js','ColorService');
c.NeutralizingKnockbackService={start:args=>{moves.push(args);return true}};
let moves=[];c.MovementService.knockback=(...args)=>{moves.push(args);return true};
c.CCService={...c.CCService,has:(e,status,now=clock)=> (e.statuses.get(status)||[]).some(v=>v.end>now),isDotImpact:i=>i?.dot===true||i?.type==='status'};
c.CombatStatusApplicationService={apply:ctx=>{burns.push(ctx);ctx.target.statuses.set(ctx.type,[{end:clock+ctx.duration}]);return true}};
c.AugmentEffectModuleService={runTrigger(){}};c.AugmentService.onConfirmedDamageDealt=()=>{};
for(const [p,n]of [['src/core/ResourceValueService.js','ResourceValueService'],['src/core/ModuleValueService.js','ModuleValueService'],['src/combat/StaminaService.js','StaminaService'],['src/render/ResourceRestoreEffectService.js','ResourceRestoreEffectService'],['src/render/CharacterTriggerEffectService.js','CharacterTriggerEffectService'],['src/network/NetworkHitAuthorityService.js','NetworkHitAuthorityService']])load(p,n);
function hit(s,t,a=ch.attacks.lmb,extra={}){return c.CharacterTriggerEffectService.run(s,'damage-dealt',{source:s,target:t,attack:a,execution:c.AttackExecutionService.create(s,a,0),impact:{type:'projectile'},amount:200,now:clock,...extra})}
function bleeding(t){t.statuses.set('bleed',[{end:clock+1000}]);return t}
test('헤브 공식 등록·체력1300/빠름/조건형 중거리 암살자·갈색 중복 없음',()=>{assert.equal(Object.keys(c.CHARACTER_DATA).length,62);assert.equal(ch.maxHealth,1200);assert.equal(ch.speed,3.75);assert.equal(ch.moveLabel,'느림');assert.equal(ch.title,'대양의 선장');assert.equal(ch.styleLabel,'조건형 딜러');for(const raw of Object.values(c.CHARACTER_DATA))if(raw.id!=='hab')assert.notEqual(raw.color.toLowerCase(),ch.color.toLowerCase());assert.ok(Object.isFrozen(ch))});
test('3종 실제 공통 발사·무기/범위 투사체·관통 정책',()=>{const e=entity();for(const key of ['lmb','rmb','counter']){shots=[];c.TriggeredAttackService.execute(e,ch.attacks[key],.7);assert.equal(shots.length,1,key);const p=shots[0];assert.equal(p.projectile.radius,key==='counter'?300:key==='rmb'?20:15);assert.equal(p.projectile.speed,key==='counter'?12:key==='rmb'?37.5:30);assert.equal(p.behavior.pierce.targets,key!=='lmb');assert.equal(p.behavior.pierce.walls,key!=='lmb');assert.equal(p.behavior.presentation.kind,key==='counter'?'range-projectile':'weapon-projectile')}});
test('평타 및 스킬은 출혈2초 / 반격은 출혈 대신 무력화 넉백',()=>{const e=entity();for(const key of ['lmb','rmb']){const t=entity({id:'enemy',teamId:'B'}),a=ch.attacks[key],ex=c.AttackExecutionService.create(e,a,0);c.AttackModuleService.onHit(e,t,a,{execution:ex},0,{type:'projectile'});assert.equal(burns.at(-1).type,'bleed');assert.equal(burns.at(-1).duration,2000);assert.equal(c.CCService.has(t,'bleed'),true)}});
test('추진 작살 넉백제거·출혈/관통유지',()=>{assert.equal(ch.attacks.rmb.modules.some(m=>m.type==='movement.knockback'),false);assert.equal(ch.attacks.lmb.cost,250);assert.equal(ch.attacks.rmb.cost,500);});
test('출혈 없는 첫 타격 회복 없음 / 이후 출혈 대상 타격50%',()=>{const e=entity({stamina:100}),t=entity({id:'enemy',teamId:'B'});hit(e,t);assert.equal(e.stamina,100);c.AttackModuleService.onHit(e,t,ch.attacks.lmb,{execution:c.AttackExecutionService.create(e,ch.attacks.lmb,0)},0,{type:'projectile'});hit(e,t);assert.equal(e.stamina,600)});
test('최대 스테미나 보정 반영·넘침 제한·모든 공격에 동일 회복',()=>{for(const a of Object.values(ch.attacks)){const e=entity({stamina:0,maxStamina:800}),t=bleeding(entity({id:'enemy',teamId:'B'}));hit(e,t,a);assert.equal(e.stamina,400);hit(e,t,a);assert.equal(e.stamina,800);hit(e,t,a);assert.equal(e.stamina,800);hit(e,t,a);assert.equal(e.stamina,800)}});
test('출혈 DOT/피해0/사망한 공격자/만료 출혈은 회복 없음',()=>{for(const mode of ['dot','zero','dead','expired']){const e=entity({stamina:0}),t=bleeding(entity({id:'enemy',teamId:'B'})),extra={};if(mode==='dot')extra.impact={type:'status',dot:true};if(mode==='zero')extra.amount=0;if(mode==='dead')e.alive=false;if(mode==='expired')clock+=1001;hit(e,t,ch.attacks.lmb,extra);assert.equal(e.stamina,0,mode);clock=1000}});
test('출혈 소환수/훈련 봇 제외·플레이어/더미 회복·피격 snapshot도 동일',()=>{for(const kind of ['summon','trainingBot','dummy','player']){const e=entity({stamina:0}),t=bleeding(entity({id:'enemy',teamId:'B',kind}));hit(e,t);assert.equal(e.stamina,['summon','trainingBot'].includes(kind)?0:500);e.stamina=0;t.statuses.clear();hit(e,t,ch.attacks.lmb,{targetStatusTypes:['bleed']});assert.equal(e.stamina,['summon','trainingBot'].includes(kind)?0:500)}});
test('반격300ms 선딜·준비소비·무력화 넉백CC 참조 검증',()=>{const m=ch.abilities.counter.trigger.modules[0];assert.equal(m.windup,300);assert.equal(m.consumeState,'counter-ready');assert.equal(c.CounterModuleService.validate(m),true);assert.equal(c.CounterModuleService.referencedCc(entity(),m).type,'movement.neutralize-knockback')});
test('설명 피해·50%는 실제 데이터 참조',()=>{const lines=ch.tooltipSkills.map(skill=>c.CharacterDescriptionService.interpolate(ch,skill));for(const text of lines)assert.ok(!text.includes('{'),text);assert.ok(lines[0].includes('50%'));assert.ok(lines[1].includes('(100)'));assert.ok(lines[2].includes('(200)'));assert.ok(lines[3].includes('(100)'))});
test('피격 권위 상태 snapshot은 늦은/빠른 상태 미러보다 우선',()=>{const e=entity({stamina:0}),t=entity({id:'enemy',teamId:'B'});hit(e,t,ch.attacks.lmb,{targetStatusTypes:['bleed']});assert.equal(e.stamina,500);bleeding(t);e.stamina=0;hit(e,t,ch.attacks.lmb,{targetStatusTypes:[]});assert.equal(e.stamina,0)});
c.ProjectileService.items=[];const packets=[];c.RoomService={sendGameplay:p=>packets.push(p)};c.Presentation={damageNumber(){}};c.SoundService={play(){}};
c.OnlineParticipantEntityService={pid:e=>e?.id,entity:id=>c.EntityService.items.get(id)};
test('실제 확정 피해 패킷 전송·수신·중복 회복 제외 / 첫 출혈 미회복',()=>{c.Training.sessionMode='online';c.OnlineDuelService.active=true;c.OnlineDuelService.roundToken=11;const source=entity({stamina:0}),target=bleeding(entity({id:'enemy',teamId:'B'}));c.EntityService.items.set(source.id,source);c.EntityService.items.set(target.id,target);const a=ch.attacks.lmb,ex=c.AttackExecutionService.create(source,a,0);assert.equal(c.NetworkHitAuthorityService.notify({source,target,attack:a,execution:ex,applied:true,healthDamage:200,amount:200,now:clock,impact:{type:'projectile'}}),true);assert.deepEqual(Array.from(packets.at(-1).targetStatusTypes),['bleed']);const packet=packets.at(-1);target.statuses.clear();target.local=false;c.NetworkHitAuthorityService.receive(target.id,packet);assert.equal(source.stamina,500);c.NetworkHitAuthorityService.receive(target.id,packet);assert.equal(source.stamina,500);source.stamina=0;bleeding(target);c.NetworkHitAuthorityService.receive(target.id,{...packet,hitSequence:packet.hitSequence+1,targetStatusTypes:[]});assert.equal(source.stamina,0);c.Training.sessionMode='training';c.OnlineDuelService.active=false});
console.log(`PASS ${passed} Hab regression groups`);
