/* 실제 사이엔 데이터·처치 이벤트/원격 확정·격 상태/절격 선택 회귀. */
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');let passed=0;
const c=vm.createContext({console,Math,Map,Set,WeakMap,EMPTY_RUNTIME_ITEMS:[],performance:{now:()=>1000}});
function load(p,n){vm.runInContext(fs.readFileSync(path.join(root,p),'utf8')+`;globalThis.${n}=${n};`,c)}
function test(name,fn){fn();passed++;console.log('PASS '+name)}
for(const n of ['characterValue','characterCount','characterSum','characterProduct','freezeCharacterData','CHARACTER_RULES'])load('src/data/'+n+'.js',n);
c.CHARACTER_DATA={cyien:vm.runInContext('('+fs.readFileSync(path.join(root,'src/data/characters/cyien.js'),'utf8')+')',c)};
load('src/data/CharacterDataService.js','CharacterDataService');const ch=c.CharacterDataService.compile('cyien');
c.RelationService={relation:(s,t)=>s===t?'self':s.teamId===t.teamId?'ally':'enemy'};
c.EntitySimulationAuthorityService={isLocal:e=>e?.local!==false};c.Training={sessionMode:'training'};c.OnlineDuelService={active:false};c.COMBAT_BUFF_DEFS={};
for(const [p,n]of [['src/core/ProgressStateService.js','ProgressStateService'],['src/core/CharacterKillProgressService.js','CharacterKillProgressService'],['src/core/GameEvents.js','GameEvents'],['src/core/RuntimeValueReferenceProviders.js','RuntimeValueReferenceProviders'],['src/core/RuntimeValueReferenceService.js','RuntimeValueReferenceService'],['src/core/TriggerConditionService.js','TriggerConditionService'],['src/core/TriggerModuleService.js','TriggerModuleService'],['src/abilities/AbilityService.js','AbilityService']])load(p,n);
for(const p of ['src/core/initialization-217.js','src/core/initialization-218.js','src/core/initialization-219.js'])vm.runInContext(fs.readFileSync(path.join(root,p),'utf8'),c);
function entity(extra={}){return{id:'source',kind:'player',teamId:'A',alive:true,local:true,character:ch,actionState:new Map(),...extra}}
function value(e){return c.ProgressStateService.state(e,'cyien-gyeok')?.value||0}
function ready(e){return c.AbilityService.resolvedInputAttack(e,ch.abilities.rmb).id===ch.attacks.rmbCharged.id}
test('모든 공격 처치 이벤트로 최대격8·절격 선택',()=>{for(const attack of Object.values(ch.attacks)){const e=entity(),t=entity({id:'enemy',teamId:'B',alive:false});c.GameEvents.emit('entity-defeated',{source:e,entity:t,attack});assert.equal(value(e),8,attack.id);assert.equal(ready(e),true)}});
test('초기 패리·부분격 패리·최대격 절격·사용 후 재처치 충전',()=>{const e=entity(),t=entity({id:'enemy',teamId:'B',alive:false});assert.equal(ready(e),false);c.ProgressStateService.apply(e,{stateKey:'cyien-gyeok',operation:'set',value:7,max:8});assert.equal(ready(e),false);c.GameEvents.emit('entity-defeated',{source:e,entity:t,attack:ch.attacks.lmb});assert.equal(ready(e),true);c.ProgressStateService.apply(e,{stateKey:'cyien-gyeok',operation:'set',value:0,max:8});assert.equal(ready(e),false);c.GameEvents.emit('entity-defeated',{source:e,entity:t,attack:ch.attacks.counter});assert.equal(ready(e),true)});
test('자신/아군/소환수 처치·사망 공격자는 충전 제외',()=>{for(const mode of ['self','ally','summon','dead-source']){const e=entity(),t=mode==='self'?e:entity({id:'target',teamId:mode==='ally'?'A':'B',kind:mode==='summon'?'summon':'player'});if(mode==='dead-source')e.alive=false;c.GameEvents.emit('entity-defeated',{source:e,entity:t,attack:ch.attacks.lmb});assert.equal(value(e),0,mode)}});
test('온라인 원격 소유자 제외·로컬 피격 확정으로 충전·JSON 복원',()=>{c.Training.sessionMode='online';c.OnlineDuelService.active=true;const e=entity(),t=entity({id:'enemy',teamId:'B',alive:false});e.local=false;c.GameEvents.emit('entity-defeated',{source:e,entity:t,attack:ch.attacks.lmb});c.GameEvents.emit('network-hit-confirmed',{source:e,target:t,attack:ch.attacks.lmb,defeated:true});assert.equal(value(e),0);e.local=true;c.GameEvents.emit('network-hit-confirmed',{source:e,target:t,attack:ch.attacks.counter,defeated:false});assert.equal(value(e),0);c.GameEvents.emit('network-hit-confirmed',{source:e,target:t,attack:ch.attacks.counter,defeated:true});assert.equal(value(e),8);c.EffectSpawnService={definitionSnapshot:x=>x};const remote=entity({local:false});c.ProgressStateService.applyRemote(remote,JSON.parse(JSON.stringify(c.ProgressStateService.serialize(e))));assert.equal(value(remote),8);assert.equal(ready(remote),true);c.Training.sessionMode='training';c.OnlineDuelService.active=false});
test('처치 충전 설명은 ALWAYS 한 곳·절격 설명 중복 제거',()=>{assert.equal(ch.tooltipSkills[0].text,'적 처치 또는 격 최대치 시 절격 활성화');assert.equal(ch.tooltipSkills.filter(s=>s.text.includes('처치')).length,1);assert.equal(ch.killRewardProgress.attackIds,undefined);assert.ok(!ch.tooltipSkills.find(s=>s.key==='RMB CHARGED').text.includes('처치'))});
console.log(`PASS ${passed} Cyien regression groups`);
